### ISSUE TITLE
Profit Sorting Tab

### ISSUE THREAD

**Issue by confubitated** [cardona150/MlbTheShow18MarketAssistant#3]
I wouldn't call this an issue but I would love for the profit after tax tab to return. Now I only see Profit % and Profit %/hour but when I was flipping a few days ago I relied on the profit after tax alone to identify cards to target. 

By the way I also dug the auto fill in for buy and sell prices, excellent work. This plugin is phenomenal, thanks for all of the work on it!

**Comment by cardona150** [comment]
Reopening for comments

**Comment by ukasuviok** [comment]
I used it as a reference just like all of the other columns to help make an informed decision.  It wasn't necessarily the main factor in deciding to flip a card or not. Plus it helps that I don't have to do quick calculations on the side to see what the potential profit may be.

**Comment by confubitated** [comment]
Thank you for the break down. I absolutely understand the reasoning on this. It was nice to have as a data point but I can certainly adjust to what seems like an optimal way to be doing it. 

I did buy a card and put it up and then leave for hours at a time so the Profit(After Tax) was useful for me to identify those that would yield the most, buy it, put for sell, and then commute to and from work etc. 

Thanks for explaining how to utilize it though, that absolutely makes sense.
