### ISSUE TITLE
Unable to see the number of orders at the same price

### ISSUE THREAD

**Issue by ukasuviok** [cardona150/MlbTheShow18MarketAssistant#4]
Sometimes there are multiple orders at the same price.  If your own order is at that price you are unable to see how many orders are placed at that price.  Example below.

![capture](https://user-images.githubusercontent.com/26655042/38965792-53405cb2-4344-11e8-9699-586e62caaf2c.PNG)

**Comment by cardona150** [comment]
I'm wondering how to solve this. If we change it to display 2 |CANCEL| someone could mistake it and think they have 2 orders for this item. I think the best solution is: Imagine a case where there are 4 orders for 1,000 stubs and you own 2 of them. Display 4 |CANCEL| |CANCEL|. This not only tell you how many orders there are for 1,000 stubs but also that you own 2 of them and you can cancel them both (if you click fast enough). What do you think?

**Comment by cardona150** [comment]
This is good enough:
![image](https://user-images.githubusercontent.com/575891/38972072-576bb3d6-4353-11e8-9ed3-f9108121ac0b.png)

**Comment by ukasuviok** [comment]
That works for me. Thanks for the quick update.
