### ISSUE TITLE
v9 player page/search issues

### ISSUE THREAD

**Issue by dannyziggy** [cardona150/MlbTheShow18MarketAssistant#6]
Just updated to V9 and have a couple of questions

I can no longer click on the player name to go to the player page - it just reloads the search page.

Also, once I get on to the player page, it does not show the orders the same way as it did previously, it looks like the coding has gone back to the SDS default and we can't cancel orders etc from the player page.

Is this intended? These were some of the core functionality for me as it allowed me to have multiple orders open in different tabs and scroll between them

**Comment by ukasuviok** [comment]
Seems like a step backwards to me.  Especially, since you're bouncing back and forth from the player details and the listings page yourself.  Now we have to search for the specific player instead of just jumping directly to it from the listings.  Either way we have to get to the player page to see all other bids/the number of buys/sells etc.

**Comment by cardona150** [comment]
I don't find the need to ever go to a specific item's page. What do you need to do this for? I can turn off all the auto-navigation but it will increase trade times, decreasing profits.

**Comment by ukasuviok** [comment]
For one I use it to see what the other bids are like, whether there is big jump or just clusters of small bid increases.  I also use it to see if the card has a bunch of buys or sells or if it's an even amount.  If it's just a bunch of sells then I probably won't want to flip it if no one is buying.  Not to mention I just use it to make all of my bids on the card.  If I want to find any other cards I just go back to my listings tab and refresh it.  Rinse and repeat.

**Comment by cardona150** [comment]
There are still ways to access individual item pages, but I think I'm just going to turn off auto navigation in the public version.

**Comment by dannyziggy** [comment]
Yeah I have to agree with ukasuviok - my main reason for using the player page was to check the amount of activity on a card, not just the transactions. See how many orders were placed, what the gaps are between orders etc. 

It just seemed like a better workflow once you had found a card that you were wanting to work with, rather than just doing your transactions from the listings page. Doing it from the listings page you aren't able to see whether there are just a lot of buy or sell orders and none of the other, or if there is a massive gap between sell orders etc.

**Comment by cardona150** [comment]
You should be able to see this information in version 10

**Comment by ukasuviok** [comment]
Is the modified details page not coming back?
